// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: critic.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/radiospiel/critic/src/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CriticServiceName is the fully-qualified name of the CriticService service.
	CriticServiceName = "critic.v1.CriticService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CriticServiceGetLastChangeProcedure is the fully-qualified name of the CriticService's
	// GetLastChange RPC.
	CriticServiceGetLastChangeProcedure = "/critic.v1.CriticService/GetLastChange"
	// CriticServiceGetDiffsProcedure is the fully-qualified name of the CriticService's GetDiffs RPC.
	CriticServiceGetDiffsProcedure = "/critic.v1.CriticService/GetDiffs"
)

// CriticServiceClient is a client for the critic.v1.CriticService service.
type CriticServiceClient interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffs returns the current diffs and state from the session.
	GetDiffs(context.Context, *connect.Request[api.GetDiffsRequest]) (*connect.Response[api.GetDiffsResponse], error)
}

// NewCriticServiceClient constructs a client for the critic.v1.CriticService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCriticServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CriticServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	return &criticServiceClient{
		getLastChange: connect.NewClient[api.GetLastChangeRequest, api.GetLastChangeResponse](
			httpClient,
			baseURL+CriticServiceGetLastChangeProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
			connect.WithClientOptions(opts...),
		),
		getDiffs: connect.NewClient[api.GetDiffsRequest, api.GetDiffsResponse](
			httpClient,
			baseURL+CriticServiceGetDiffsProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiffs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// criticServiceClient implements CriticServiceClient.
type criticServiceClient struct {
	getLastChange *connect.Client[api.GetLastChangeRequest, api.GetLastChangeResponse]
	getDiffs      *connect.Client[api.GetDiffsRequest, api.GetDiffsResponse]
}

// GetLastChange calls critic.v1.CriticService.GetLastChange.
func (c *criticServiceClient) GetLastChange(ctx context.Context, req *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return c.getLastChange.CallUnary(ctx, req)
}

// GetDiffs calls critic.v1.CriticService.GetDiffs.
func (c *criticServiceClient) GetDiffs(ctx context.Context, req *connect.Request[api.GetDiffsRequest]) (*connect.Response[api.GetDiffsResponse], error) {
	return c.getDiffs.CallUnary(ctx, req)
}

// CriticServiceHandler is an implementation of the critic.v1.CriticService service.
type CriticServiceHandler interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffs returns the current diffs and state from the session.
	GetDiffs(context.Context, *connect.Request[api.GetDiffsRequest]) (*connect.Response[api.GetDiffsResponse], error)
}

// NewCriticServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCriticServiceHandler(svc CriticServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	criticServiceGetLastChangeHandler := connect.NewUnaryHandler(
		CriticServiceGetLastChangeProcedure,
		svc.GetLastChange,
		connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffsHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffsProcedure,
		svc.GetDiffs,
		connect.WithSchema(criticServiceMethods.ByName("GetDiffs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/critic.v1.CriticService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CriticServiceGetLastChangeProcedure:
			criticServiceGetLastChangeHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffsProcedure:
			criticServiceGetDiffsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCriticServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCriticServiceHandler struct{}

func (UnimplementedCriticServiceHandler) GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetLastChange is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiffs(context.Context, *connect.Request[api.GetDiffsRequest]) (*connect.Response[api.GetDiffsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiffs is not implemented"))
}
