// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: critic.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/radiospiel/critic/src/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CriticServiceName is the fully-qualified name of the CriticService service.
	CriticServiceName = "critic.v1.CriticService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CriticServiceGetLastChangeProcedure is the fully-qualified name of the CriticService's
	// GetLastChange RPC.
	CriticServiceGetLastChangeProcedure = "/critic.v1.CriticService/GetLastChange"
	// CriticServiceGetDiffSummaryProcedure is the fully-qualified name of the CriticService's
	// GetDiffSummary RPC.
	CriticServiceGetDiffSummaryProcedure = "/critic.v1.CriticService/GetDiffSummary"
	// CriticServiceGetDiffProcedure is the fully-qualified name of the CriticService's GetDiff RPC.
	CriticServiceGetDiffProcedure = "/critic.v1.CriticService/GetDiff"
	// CriticServiceGetFileProcedure is the fully-qualified name of the CriticService's GetFile RPC.
	CriticServiceGetFileProcedure = "/critic.v1.CriticService/GetFile"
)

// CriticServiceClient is a client for the critic.v1.CriticService service.
type CriticServiceClient interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffSummary returns the current diff summary (file list without hunks) and state.
	GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error)
	// GetDiff returns the full diff for a specific file path.
	GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error)
	// GetFile returns the content of a file at a specific path.
	GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error)
}

// NewCriticServiceClient constructs a client for the critic.v1.CriticService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCriticServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CriticServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	return &criticServiceClient{
		getLastChange: connect.NewClient[api.GetLastChangeRequest, api.GetLastChangeResponse](
			httpClient,
			baseURL+CriticServiceGetLastChangeProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
			connect.WithClientOptions(opts...),
		),
		getDiffSummary: connect.NewClient[api.GetDiffSummaryRequest, api.GetDiffSummaryResponse](
			httpClient,
			baseURL+CriticServiceGetDiffSummaryProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiffSummary")),
			connect.WithClientOptions(opts...),
		),
		getDiff: connect.NewClient[api.GetDiffRequest, api.GetDiffResponse](
			httpClient,
			baseURL+CriticServiceGetDiffProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiff")),
			connect.WithClientOptions(opts...),
		),
		getFile: connect.NewClient[api.GetFileRequest, api.GetFileResponse](
			httpClient,
			baseURL+CriticServiceGetFileProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetFile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// criticServiceClient implements CriticServiceClient.
type criticServiceClient struct {
	getLastChange  *connect.Client[api.GetLastChangeRequest, api.GetLastChangeResponse]
	getDiffSummary *connect.Client[api.GetDiffSummaryRequest, api.GetDiffSummaryResponse]
	getDiff        *connect.Client[api.GetDiffRequest, api.GetDiffResponse]
	getFile        *connect.Client[api.GetFileRequest, api.GetFileResponse]
}

// GetLastChange calls critic.v1.CriticService.GetLastChange.
func (c *criticServiceClient) GetLastChange(ctx context.Context, req *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return c.getLastChange.CallUnary(ctx, req)
}

// GetDiffSummary calls critic.v1.CriticService.GetDiffSummary.
func (c *criticServiceClient) GetDiffSummary(ctx context.Context, req *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error) {
	return c.getDiffSummary.CallUnary(ctx, req)
}

// GetDiff calls critic.v1.CriticService.GetDiff.
func (c *criticServiceClient) GetDiff(ctx context.Context, req *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error) {
	return c.getDiff.CallUnary(ctx, req)
}

// GetFile calls critic.v1.CriticService.GetFile.
func (c *criticServiceClient) GetFile(ctx context.Context, req *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error) {
	return c.getFile.CallUnary(ctx, req)
}

// CriticServiceHandler is an implementation of the critic.v1.CriticService service.
type CriticServiceHandler interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffSummary returns the current diff summary (file list without hunks) and state.
	GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error)
	// GetDiff returns the full diff for a specific file path.
	GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error)
	// GetFile returns the content of a file at a specific path.
	GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error)
}

// NewCriticServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCriticServiceHandler(svc CriticServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	criticServiceGetLastChangeHandler := connect.NewUnaryHandler(
		CriticServiceGetLastChangeProcedure,
		svc.GetLastChange,
		connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffSummaryHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffSummaryProcedure,
		svc.GetDiffSummary,
		connect.WithSchema(criticServiceMethods.ByName("GetDiffSummary")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffProcedure,
		svc.GetDiff,
		connect.WithSchema(criticServiceMethods.ByName("GetDiff")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetFileHandler := connect.NewUnaryHandler(
		CriticServiceGetFileProcedure,
		svc.GetFile,
		connect.WithSchema(criticServiceMethods.ByName("GetFile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/critic.v1.CriticService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CriticServiceGetLastChangeProcedure:
			criticServiceGetLastChangeHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffSummaryProcedure:
			criticServiceGetDiffSummaryHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffProcedure:
			criticServiceGetDiffHandler.ServeHTTP(w, r)
		case CriticServiceGetFileProcedure:
			criticServiceGetFileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCriticServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCriticServiceHandler struct{}

func (UnimplementedCriticServiceHandler) GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetLastChange is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiffSummary is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiff is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetFile is not implemented"))
}
