// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: critic.proto

package apiconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	api "github.com/radiospiel/critic/src/api"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CriticServiceName is the fully-qualified name of the CriticService service.
	CriticServiceName = "critic.v1.CriticService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CriticServiceGetLastChangeProcedure is the fully-qualified name of the CriticService's
	// GetLastChange RPC.
	CriticServiceGetLastChangeProcedure = "/critic.v1.CriticService/GetLastChange"
	// CriticServiceGetDiffSummaryProcedure is the fully-qualified name of the CriticService's
	// GetDiffSummary RPC.
	CriticServiceGetDiffSummaryProcedure = "/critic.v1.CriticService/GetDiffSummary"
	// CriticServiceGetDiffProcedure is the fully-qualified name of the CriticService's GetDiff RPC.
	CriticServiceGetDiffProcedure = "/critic.v1.CriticService/GetDiff"
	// CriticServiceGetFileProcedure is the fully-qualified name of the CriticService's GetFile RPC.
	CriticServiceGetFileProcedure = "/critic.v1.CriticService/GetFile"
	// CriticServiceCreateConversationProcedure is the fully-qualified name of the CriticService's
	// CreateConversation RPC.
	CriticServiceCreateConversationProcedure = "/critic.v1.CriticService/CreateConversation"
	// CriticServiceGetConversationsProcedure is the fully-qualified name of the CriticService's
	// GetConversations RPC.
	CriticServiceGetConversationsProcedure = "/critic.v1.CriticService/GetConversations"
	// CriticServiceGetConversationsSummaryProcedure is the fully-qualified name of the CriticService's
	// GetConversationsSummary RPC.
	CriticServiceGetConversationsSummaryProcedure = "/critic.v1.CriticService/GetConversationsSummary"
	// CriticServiceReplyToConversationProcedure is the fully-qualified name of the CriticService's
	// ReplyToConversation RPC.
	CriticServiceReplyToConversationProcedure = "/critic.v1.CriticService/ReplyToConversation"
	// CriticServiceMarkConversationAsProcedure is the fully-qualified name of the CriticService's
	// MarkConversationAs RPC.
	CriticServiceMarkConversationAsProcedure = "/critic.v1.CriticService/MarkConversationAs"
	// CriticServiceGetDiffBasesProcedure is the fully-qualified name of the CriticService's
	// GetDiffBases RPC.
	CriticServiceGetDiffBasesProcedure = "/critic.v1.CriticService/GetDiffBases"
	// CriticServiceSetDiffBaseProcedure is the fully-qualified name of the CriticService's SetDiffBase
	// RPC.
	CriticServiceSetDiffBaseProcedure = "/critic.v1.CriticService/SetDiffBase"
	// CriticServiceWatchFileProcedure is the fully-qualified name of the CriticService's WatchFile RPC.
	CriticServiceWatchFileProcedure = "/critic.v1.CriticService/WatchFile"
	// CriticServiceGetConfigProcedure is the fully-qualified name of the CriticService's GetConfig RPC.
	CriticServiceGetConfigProcedure = "/critic.v1.CriticService/GetConfig"
	// CriticServiceGetRootConversationProcedure is the fully-qualified name of the CriticService's
	// GetRootConversation RPC.
	CriticServiceGetRootConversationProcedure = "/critic.v1.CriticService/GetRootConversation"
	// CriticServiceGetProjectConfigProcedure is the fully-qualified name of the CriticService's
	// GetProjectConfig RPC.
	CriticServiceGetProjectConfigProcedure = "/critic.v1.CriticService/GetProjectConfig"
	// CriticServiceCreateExplanationProcedure is the fully-qualified name of the CriticService's
	// CreateExplanation RPC.
	CriticServiceCreateExplanationProcedure = "/critic.v1.CriticService/CreateExplanation"
	// CriticServiceSetClaudeSessionProcedure is the fully-qualified name of the CriticService's
	// SetClaudeSession RPC.
	CriticServiceSetClaudeSessionProcedure = "/critic.v1.CriticService/SetClaudeSession"
	// CriticServiceInjectPromptProcedure is the fully-qualified name of the CriticService's
	// InjectPrompt RPC.
	CriticServiceInjectPromptProcedure = "/critic.v1.CriticService/InjectPrompt"
)

// CriticServiceClient is a client for the critic.v1.CriticService service.
type CriticServiceClient interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffSummary returns the current diff summary (file list without hunks) and state.
	GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error)
	// GetDiff returns the full diff for a specific file path.
	GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error)
	// GetFile returns the content of a file at a specific path.
	GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error)
	// CreateConversation creates a new conversation (comment thread) on a diff line.
	CreateConversation(context.Context, *connect.Request[api.CreateConversationRequest]) (*connect.Response[api.CreateConversationResponse], error)
	// GetConversations returns conversations matching the given filters.
	// If paths is empty, returns conversations across all files.
	// If statuses is empty, returns conversations with any status.
	GetConversations(context.Context, *connect.Request[api.GetConversationsRequest]) (*connect.Response[api.GetConversationsResponse], error)
	// GetConversationsSummary returns conversation counts and status per file path.
	GetConversationsSummary(context.Context, *connect.Request[api.GetConversationsSummaryRequest]) (*connect.Response[api.GetConversationsSummaryResponse], error)
	// ReplyToConversation adds a reply message to an existing conversation.
	ReplyToConversation(context.Context, *connect.Request[api.ReplyToConversationRequest]) (*connect.Response[api.ReplyToConversationResponse], error)
	// MarkConversationAs updates the status of a conversation (resolve, unresolve, archive).
	MarkConversationAs(context.Context, *connect.Request[api.MarkConversationAsRequest]) (*connect.Response[api.MarkConversationAsResponse], error)
	// GetDiffBases returns available diff bases and the current one.
	GetDiffBases(context.Context, *connect.Request[api.GetDiffBasesRequest]) (*connect.Response[api.GetDiffBasesResponse], error)
	// SetDiffBase sets the current diff base.
	SetDiffBase(context.Context, *connect.Request[api.SetDiffBaseRequest]) (*connect.Response[api.SetDiffBaseResponse], error)
	// WatchFile tells the server to watch a specific file for changes.
	WatchFile(context.Context, *connect.Request[api.WatchFileRequest]) (*connect.Response[api.WatchFileResponse], error)
	// GetConfig returns server configuration for the frontend.
	GetConfig(context.Context, *connect.Request[api.GetConfigRequest]) (*connect.Response[api.GetConfigResponse], error)
	// GetRootConversation returns the root conversation (global announcements).
	GetRootConversation(context.Context, *connect.Request[api.GetRootConversationRequest]) (*connect.Response[api.GetRootConversationResponse], error)
	// GetProjectConfig returns the parsed project.critic configuration.
	GetProjectConfig(context.Context, *connect.Request[api.GetProjectConfigRequest]) (*connect.Response[api.GetProjectConfigResponse], error)
	// CreateExplanation creates a new explanation (informal annotation) on a code line.
	CreateExplanation(context.Context, *connect.Request[api.CreateExplanationRequest]) (*connect.Response[api.CreateExplanationResponse], error)
	// SetClaudeSession stores the Claude Code session ID for prompt injection.
	SetClaudeSession(context.Context, *connect.Request[api.SetClaudeSessionRequest]) (*connect.Response[api.SetClaudeSessionResponse], error)
	// InjectPrompt sends a prompt to the connected Claude Code session.
	InjectPrompt(context.Context, *connect.Request[api.InjectPromptRequest]) (*connect.Response[api.InjectPromptResponse], error)
}

// NewCriticServiceClient constructs a client for the critic.v1.CriticService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCriticServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CriticServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	return &criticServiceClient{
		getLastChange: connect.NewClient[api.GetLastChangeRequest, api.GetLastChangeResponse](
			httpClient,
			baseURL+CriticServiceGetLastChangeProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
			connect.WithClientOptions(opts...),
		),
		getDiffSummary: connect.NewClient[api.GetDiffSummaryRequest, api.GetDiffSummaryResponse](
			httpClient,
			baseURL+CriticServiceGetDiffSummaryProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiffSummary")),
			connect.WithClientOptions(opts...),
		),
		getDiff: connect.NewClient[api.GetDiffRequest, api.GetDiffResponse](
			httpClient,
			baseURL+CriticServiceGetDiffProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiff")),
			connect.WithClientOptions(opts...),
		),
		getFile: connect.NewClient[api.GetFileRequest, api.GetFileResponse](
			httpClient,
			baseURL+CriticServiceGetFileProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetFile")),
			connect.WithClientOptions(opts...),
		),
		createConversation: connect.NewClient[api.CreateConversationRequest, api.CreateConversationResponse](
			httpClient,
			baseURL+CriticServiceCreateConversationProcedure,
			connect.WithSchema(criticServiceMethods.ByName("CreateConversation")),
			connect.WithClientOptions(opts...),
		),
		getConversations: connect.NewClient[api.GetConversationsRequest, api.GetConversationsResponse](
			httpClient,
			baseURL+CriticServiceGetConversationsProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetConversations")),
			connect.WithClientOptions(opts...),
		),
		getConversationsSummary: connect.NewClient[api.GetConversationsSummaryRequest, api.GetConversationsSummaryResponse](
			httpClient,
			baseURL+CriticServiceGetConversationsSummaryProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetConversationsSummary")),
			connect.WithClientOptions(opts...),
		),
		replyToConversation: connect.NewClient[api.ReplyToConversationRequest, api.ReplyToConversationResponse](
			httpClient,
			baseURL+CriticServiceReplyToConversationProcedure,
			connect.WithSchema(criticServiceMethods.ByName("ReplyToConversation")),
			connect.WithClientOptions(opts...),
		),
		markConversationAs: connect.NewClient[api.MarkConversationAsRequest, api.MarkConversationAsResponse](
			httpClient,
			baseURL+CriticServiceMarkConversationAsProcedure,
			connect.WithSchema(criticServiceMethods.ByName("MarkConversationAs")),
			connect.WithClientOptions(opts...),
		),
		getDiffBases: connect.NewClient[api.GetDiffBasesRequest, api.GetDiffBasesResponse](
			httpClient,
			baseURL+CriticServiceGetDiffBasesProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetDiffBases")),
			connect.WithClientOptions(opts...),
		),
		setDiffBase: connect.NewClient[api.SetDiffBaseRequest, api.SetDiffBaseResponse](
			httpClient,
			baseURL+CriticServiceSetDiffBaseProcedure,
			connect.WithSchema(criticServiceMethods.ByName("SetDiffBase")),
			connect.WithClientOptions(opts...),
		),
		watchFile: connect.NewClient[api.WatchFileRequest, api.WatchFileResponse](
			httpClient,
			baseURL+CriticServiceWatchFileProcedure,
			connect.WithSchema(criticServiceMethods.ByName("WatchFile")),
			connect.WithClientOptions(opts...),
		),
		getConfig: connect.NewClient[api.GetConfigRequest, api.GetConfigResponse](
			httpClient,
			baseURL+CriticServiceGetConfigProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetConfig")),
			connect.WithClientOptions(opts...),
		),
		getRootConversation: connect.NewClient[api.GetRootConversationRequest, api.GetRootConversationResponse](
			httpClient,
			baseURL+CriticServiceGetRootConversationProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetRootConversation")),
			connect.WithClientOptions(opts...),
		),
		getProjectConfig: connect.NewClient[api.GetProjectConfigRequest, api.GetProjectConfigResponse](
			httpClient,
			baseURL+CriticServiceGetProjectConfigProcedure,
			connect.WithSchema(criticServiceMethods.ByName("GetProjectConfig")),
			connect.WithClientOptions(opts...),
		),
		createExplanation: connect.NewClient[api.CreateExplanationRequest, api.CreateExplanationResponse](
			httpClient,
			baseURL+CriticServiceCreateExplanationProcedure,
			connect.WithSchema(criticServiceMethods.ByName("CreateExplanation")),
			connect.WithClientOptions(opts...),
		),
		setClaudeSession: connect.NewClient[api.SetClaudeSessionRequest, api.SetClaudeSessionResponse](
			httpClient,
			baseURL+CriticServiceSetClaudeSessionProcedure,
			connect.WithSchema(criticServiceMethods.ByName("SetClaudeSession")),
			connect.WithClientOptions(opts...),
		),
		injectPrompt: connect.NewClient[api.InjectPromptRequest, api.InjectPromptResponse](
			httpClient,
			baseURL+CriticServiceInjectPromptProcedure,
			connect.WithSchema(criticServiceMethods.ByName("InjectPrompt")),
			connect.WithClientOptions(opts...),
		),
	}
}

// criticServiceClient implements CriticServiceClient.
type criticServiceClient struct {
	getLastChange           *connect.Client[api.GetLastChangeRequest, api.GetLastChangeResponse]
	getDiffSummary          *connect.Client[api.GetDiffSummaryRequest, api.GetDiffSummaryResponse]
	getDiff                 *connect.Client[api.GetDiffRequest, api.GetDiffResponse]
	getFile                 *connect.Client[api.GetFileRequest, api.GetFileResponse]
	createConversation      *connect.Client[api.CreateConversationRequest, api.CreateConversationResponse]
	getConversations        *connect.Client[api.GetConversationsRequest, api.GetConversationsResponse]
	getConversationsSummary *connect.Client[api.GetConversationsSummaryRequest, api.GetConversationsSummaryResponse]
	replyToConversation     *connect.Client[api.ReplyToConversationRequest, api.ReplyToConversationResponse]
	markConversationAs      *connect.Client[api.MarkConversationAsRequest, api.MarkConversationAsResponse]
	getDiffBases            *connect.Client[api.GetDiffBasesRequest, api.GetDiffBasesResponse]
	setDiffBase             *connect.Client[api.SetDiffBaseRequest, api.SetDiffBaseResponse]
	watchFile               *connect.Client[api.WatchFileRequest, api.WatchFileResponse]
	getConfig               *connect.Client[api.GetConfigRequest, api.GetConfigResponse]
	getRootConversation     *connect.Client[api.GetRootConversationRequest, api.GetRootConversationResponse]
	getProjectConfig        *connect.Client[api.GetProjectConfigRequest, api.GetProjectConfigResponse]
	createExplanation       *connect.Client[api.CreateExplanationRequest, api.CreateExplanationResponse]
	setClaudeSession        *connect.Client[api.SetClaudeSessionRequest, api.SetClaudeSessionResponse]
	injectPrompt            *connect.Client[api.InjectPromptRequest, api.InjectPromptResponse]
}

// GetLastChange calls critic.v1.CriticService.GetLastChange.
func (c *criticServiceClient) GetLastChange(ctx context.Context, req *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return c.getLastChange.CallUnary(ctx, req)
}

// GetDiffSummary calls critic.v1.CriticService.GetDiffSummary.
func (c *criticServiceClient) GetDiffSummary(ctx context.Context, req *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error) {
	return c.getDiffSummary.CallUnary(ctx, req)
}

// GetDiff calls critic.v1.CriticService.GetDiff.
func (c *criticServiceClient) GetDiff(ctx context.Context, req *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error) {
	return c.getDiff.CallUnary(ctx, req)
}

// GetFile calls critic.v1.CriticService.GetFile.
func (c *criticServiceClient) GetFile(ctx context.Context, req *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error) {
	return c.getFile.CallUnary(ctx, req)
}

// CreateConversation calls critic.v1.CriticService.CreateConversation.
func (c *criticServiceClient) CreateConversation(ctx context.Context, req *connect.Request[api.CreateConversationRequest]) (*connect.Response[api.CreateConversationResponse], error) {
	return c.createConversation.CallUnary(ctx, req)
}

// GetConversations calls critic.v1.CriticService.GetConversations.
func (c *criticServiceClient) GetConversations(ctx context.Context, req *connect.Request[api.GetConversationsRequest]) (*connect.Response[api.GetConversationsResponse], error) {
	return c.getConversations.CallUnary(ctx, req)
}

// GetConversationsSummary calls critic.v1.CriticService.GetConversationsSummary.
func (c *criticServiceClient) GetConversationsSummary(ctx context.Context, req *connect.Request[api.GetConversationsSummaryRequest]) (*connect.Response[api.GetConversationsSummaryResponse], error) {
	return c.getConversationsSummary.CallUnary(ctx, req)
}

// ReplyToConversation calls critic.v1.CriticService.ReplyToConversation.
func (c *criticServiceClient) ReplyToConversation(ctx context.Context, req *connect.Request[api.ReplyToConversationRequest]) (*connect.Response[api.ReplyToConversationResponse], error) {
	return c.replyToConversation.CallUnary(ctx, req)
}

// MarkConversationAs calls critic.v1.CriticService.MarkConversationAs.
func (c *criticServiceClient) MarkConversationAs(ctx context.Context, req *connect.Request[api.MarkConversationAsRequest]) (*connect.Response[api.MarkConversationAsResponse], error) {
	return c.markConversationAs.CallUnary(ctx, req)
}

// GetDiffBases calls critic.v1.CriticService.GetDiffBases.
func (c *criticServiceClient) GetDiffBases(ctx context.Context, req *connect.Request[api.GetDiffBasesRequest]) (*connect.Response[api.GetDiffBasesResponse], error) {
	return c.getDiffBases.CallUnary(ctx, req)
}

// SetDiffBase calls critic.v1.CriticService.SetDiffBase.
func (c *criticServiceClient) SetDiffBase(ctx context.Context, req *connect.Request[api.SetDiffBaseRequest]) (*connect.Response[api.SetDiffBaseResponse], error) {
	return c.setDiffBase.CallUnary(ctx, req)
}

// WatchFile calls critic.v1.CriticService.WatchFile.
func (c *criticServiceClient) WatchFile(ctx context.Context, req *connect.Request[api.WatchFileRequest]) (*connect.Response[api.WatchFileResponse], error) {
	return c.watchFile.CallUnary(ctx, req)
}

// GetConfig calls critic.v1.CriticService.GetConfig.
func (c *criticServiceClient) GetConfig(ctx context.Context, req *connect.Request[api.GetConfigRequest]) (*connect.Response[api.GetConfigResponse], error) {
	return c.getConfig.CallUnary(ctx, req)
}

// GetRootConversation calls critic.v1.CriticService.GetRootConversation.
func (c *criticServiceClient) GetRootConversation(ctx context.Context, req *connect.Request[api.GetRootConversationRequest]) (*connect.Response[api.GetRootConversationResponse], error) {
	return c.getRootConversation.CallUnary(ctx, req)
}

// GetProjectConfig calls critic.v1.CriticService.GetProjectConfig.
func (c *criticServiceClient) GetProjectConfig(ctx context.Context, req *connect.Request[api.GetProjectConfigRequest]) (*connect.Response[api.GetProjectConfigResponse], error) {
	return c.getProjectConfig.CallUnary(ctx, req)
}

// CreateExplanation calls critic.v1.CriticService.CreateExplanation.
func (c *criticServiceClient) CreateExplanation(ctx context.Context, req *connect.Request[api.CreateExplanationRequest]) (*connect.Response[api.CreateExplanationResponse], error) {
	return c.createExplanation.CallUnary(ctx, req)
}

// SetClaudeSession calls critic.v1.CriticService.SetClaudeSession.
func (c *criticServiceClient) SetClaudeSession(ctx context.Context, req *connect.Request[api.SetClaudeSessionRequest]) (*connect.Response[api.SetClaudeSessionResponse], error) {
	return c.setClaudeSession.CallUnary(ctx, req)
}

// InjectPrompt calls critic.v1.CriticService.InjectPrompt.
func (c *criticServiceClient) InjectPrompt(ctx context.Context, req *connect.Request[api.InjectPromptRequest]) (*connect.Response[api.InjectPromptResponse], error) {
	return c.injectPrompt.CallUnary(ctx, req)
}

// CriticServiceHandler is an implementation of the critic.v1.CriticService service.
type CriticServiceHandler interface {
	// GetLastChange returns the timestamp of the last change.
	GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error)
	// GetDiffSummary returns the current diff summary (file list without hunks) and state.
	GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error)
	// GetDiff returns the full diff for a specific file path.
	GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error)
	// GetFile returns the content of a file at a specific path.
	GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error)
	// CreateConversation creates a new conversation (comment thread) on a diff line.
	CreateConversation(context.Context, *connect.Request[api.CreateConversationRequest]) (*connect.Response[api.CreateConversationResponse], error)
	// GetConversations returns conversations matching the given filters.
	// If paths is empty, returns conversations across all files.
	// If statuses is empty, returns conversations with any status.
	GetConversations(context.Context, *connect.Request[api.GetConversationsRequest]) (*connect.Response[api.GetConversationsResponse], error)
	// GetConversationsSummary returns conversation counts and status per file path.
	GetConversationsSummary(context.Context, *connect.Request[api.GetConversationsSummaryRequest]) (*connect.Response[api.GetConversationsSummaryResponse], error)
	// ReplyToConversation adds a reply message to an existing conversation.
	ReplyToConversation(context.Context, *connect.Request[api.ReplyToConversationRequest]) (*connect.Response[api.ReplyToConversationResponse], error)
	// MarkConversationAs updates the status of a conversation (resolve, unresolve, archive).
	MarkConversationAs(context.Context, *connect.Request[api.MarkConversationAsRequest]) (*connect.Response[api.MarkConversationAsResponse], error)
	// GetDiffBases returns available diff bases and the current one.
	GetDiffBases(context.Context, *connect.Request[api.GetDiffBasesRequest]) (*connect.Response[api.GetDiffBasesResponse], error)
	// SetDiffBase sets the current diff base.
	SetDiffBase(context.Context, *connect.Request[api.SetDiffBaseRequest]) (*connect.Response[api.SetDiffBaseResponse], error)
	// WatchFile tells the server to watch a specific file for changes.
	WatchFile(context.Context, *connect.Request[api.WatchFileRequest]) (*connect.Response[api.WatchFileResponse], error)
	// GetConfig returns server configuration for the frontend.
	GetConfig(context.Context, *connect.Request[api.GetConfigRequest]) (*connect.Response[api.GetConfigResponse], error)
	// GetRootConversation returns the root conversation (global announcements).
	GetRootConversation(context.Context, *connect.Request[api.GetRootConversationRequest]) (*connect.Response[api.GetRootConversationResponse], error)
	// GetProjectConfig returns the parsed project.critic configuration.
	GetProjectConfig(context.Context, *connect.Request[api.GetProjectConfigRequest]) (*connect.Response[api.GetProjectConfigResponse], error)
	// CreateExplanation creates a new explanation (informal annotation) on a code line.
	CreateExplanation(context.Context, *connect.Request[api.CreateExplanationRequest]) (*connect.Response[api.CreateExplanationResponse], error)
	// SetClaudeSession stores the Claude Code session ID for prompt injection.
	SetClaudeSession(context.Context, *connect.Request[api.SetClaudeSessionRequest]) (*connect.Response[api.SetClaudeSessionResponse], error)
	// InjectPrompt sends a prompt to the connected Claude Code session.
	InjectPrompt(context.Context, *connect.Request[api.InjectPromptRequest]) (*connect.Response[api.InjectPromptResponse], error)
}

// NewCriticServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCriticServiceHandler(svc CriticServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	criticServiceMethods := api.File_critic_proto.Services().ByName("CriticService").Methods()
	criticServiceGetLastChangeHandler := connect.NewUnaryHandler(
		CriticServiceGetLastChangeProcedure,
		svc.GetLastChange,
		connect.WithSchema(criticServiceMethods.ByName("GetLastChange")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffSummaryHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffSummaryProcedure,
		svc.GetDiffSummary,
		connect.WithSchema(criticServiceMethods.ByName("GetDiffSummary")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffProcedure,
		svc.GetDiff,
		connect.WithSchema(criticServiceMethods.ByName("GetDiff")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetFileHandler := connect.NewUnaryHandler(
		CriticServiceGetFileProcedure,
		svc.GetFile,
		connect.WithSchema(criticServiceMethods.ByName("GetFile")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceCreateConversationHandler := connect.NewUnaryHandler(
		CriticServiceCreateConversationProcedure,
		svc.CreateConversation,
		connect.WithSchema(criticServiceMethods.ByName("CreateConversation")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetConversationsHandler := connect.NewUnaryHandler(
		CriticServiceGetConversationsProcedure,
		svc.GetConversations,
		connect.WithSchema(criticServiceMethods.ByName("GetConversations")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetConversationsSummaryHandler := connect.NewUnaryHandler(
		CriticServiceGetConversationsSummaryProcedure,
		svc.GetConversationsSummary,
		connect.WithSchema(criticServiceMethods.ByName("GetConversationsSummary")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceReplyToConversationHandler := connect.NewUnaryHandler(
		CriticServiceReplyToConversationProcedure,
		svc.ReplyToConversation,
		connect.WithSchema(criticServiceMethods.ByName("ReplyToConversation")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceMarkConversationAsHandler := connect.NewUnaryHandler(
		CriticServiceMarkConversationAsProcedure,
		svc.MarkConversationAs,
		connect.WithSchema(criticServiceMethods.ByName("MarkConversationAs")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetDiffBasesHandler := connect.NewUnaryHandler(
		CriticServiceGetDiffBasesProcedure,
		svc.GetDiffBases,
		connect.WithSchema(criticServiceMethods.ByName("GetDiffBases")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceSetDiffBaseHandler := connect.NewUnaryHandler(
		CriticServiceSetDiffBaseProcedure,
		svc.SetDiffBase,
		connect.WithSchema(criticServiceMethods.ByName("SetDiffBase")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceWatchFileHandler := connect.NewUnaryHandler(
		CriticServiceWatchFileProcedure,
		svc.WatchFile,
		connect.WithSchema(criticServiceMethods.ByName("WatchFile")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetConfigHandler := connect.NewUnaryHandler(
		CriticServiceGetConfigProcedure,
		svc.GetConfig,
		connect.WithSchema(criticServiceMethods.ByName("GetConfig")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetRootConversationHandler := connect.NewUnaryHandler(
		CriticServiceGetRootConversationProcedure,
		svc.GetRootConversation,
		connect.WithSchema(criticServiceMethods.ByName("GetRootConversation")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceGetProjectConfigHandler := connect.NewUnaryHandler(
		CriticServiceGetProjectConfigProcedure,
		svc.GetProjectConfig,
		connect.WithSchema(criticServiceMethods.ByName("GetProjectConfig")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceCreateExplanationHandler := connect.NewUnaryHandler(
		CriticServiceCreateExplanationProcedure,
		svc.CreateExplanation,
		connect.WithSchema(criticServiceMethods.ByName("CreateExplanation")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceSetClaudeSessionHandler := connect.NewUnaryHandler(
		CriticServiceSetClaudeSessionProcedure,
		svc.SetClaudeSession,
		connect.WithSchema(criticServiceMethods.ByName("SetClaudeSession")),
		connect.WithHandlerOptions(opts...),
	)
	criticServiceInjectPromptHandler := connect.NewUnaryHandler(
		CriticServiceInjectPromptProcedure,
		svc.InjectPrompt,
		connect.WithSchema(criticServiceMethods.ByName("InjectPrompt")),
		connect.WithHandlerOptions(opts...),
	)
	return "/critic.v1.CriticService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CriticServiceGetLastChangeProcedure:
			criticServiceGetLastChangeHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffSummaryProcedure:
			criticServiceGetDiffSummaryHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffProcedure:
			criticServiceGetDiffHandler.ServeHTTP(w, r)
		case CriticServiceGetFileProcedure:
			criticServiceGetFileHandler.ServeHTTP(w, r)
		case CriticServiceCreateConversationProcedure:
			criticServiceCreateConversationHandler.ServeHTTP(w, r)
		case CriticServiceGetConversationsProcedure:
			criticServiceGetConversationsHandler.ServeHTTP(w, r)
		case CriticServiceGetConversationsSummaryProcedure:
			criticServiceGetConversationsSummaryHandler.ServeHTTP(w, r)
		case CriticServiceReplyToConversationProcedure:
			criticServiceReplyToConversationHandler.ServeHTTP(w, r)
		case CriticServiceMarkConversationAsProcedure:
			criticServiceMarkConversationAsHandler.ServeHTTP(w, r)
		case CriticServiceGetDiffBasesProcedure:
			criticServiceGetDiffBasesHandler.ServeHTTP(w, r)
		case CriticServiceSetDiffBaseProcedure:
			criticServiceSetDiffBaseHandler.ServeHTTP(w, r)
		case CriticServiceWatchFileProcedure:
			criticServiceWatchFileHandler.ServeHTTP(w, r)
		case CriticServiceGetConfigProcedure:
			criticServiceGetConfigHandler.ServeHTTP(w, r)
		case CriticServiceGetRootConversationProcedure:
			criticServiceGetRootConversationHandler.ServeHTTP(w, r)
		case CriticServiceGetProjectConfigProcedure:
			criticServiceGetProjectConfigHandler.ServeHTTP(w, r)
		case CriticServiceCreateExplanationProcedure:
			criticServiceCreateExplanationHandler.ServeHTTP(w, r)
		case CriticServiceSetClaudeSessionProcedure:
			criticServiceSetClaudeSessionHandler.ServeHTTP(w, r)
		case CriticServiceInjectPromptProcedure:
			criticServiceInjectPromptHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCriticServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCriticServiceHandler struct{}

func (UnimplementedCriticServiceHandler) GetLastChange(context.Context, *connect.Request[api.GetLastChangeRequest]) (*connect.Response[api.GetLastChangeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetLastChange is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiffSummary(context.Context, *connect.Request[api.GetDiffSummaryRequest]) (*connect.Response[api.GetDiffSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiffSummary is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiff(context.Context, *connect.Request[api.GetDiffRequest]) (*connect.Response[api.GetDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiff is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetFile(context.Context, *connect.Request[api.GetFileRequest]) (*connect.Response[api.GetFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetFile is not implemented"))
}

func (UnimplementedCriticServiceHandler) CreateConversation(context.Context, *connect.Request[api.CreateConversationRequest]) (*connect.Response[api.CreateConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.CreateConversation is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetConversations(context.Context, *connect.Request[api.GetConversationsRequest]) (*connect.Response[api.GetConversationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetConversations is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetConversationsSummary(context.Context, *connect.Request[api.GetConversationsSummaryRequest]) (*connect.Response[api.GetConversationsSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetConversationsSummary is not implemented"))
}

func (UnimplementedCriticServiceHandler) ReplyToConversation(context.Context, *connect.Request[api.ReplyToConversationRequest]) (*connect.Response[api.ReplyToConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.ReplyToConversation is not implemented"))
}

func (UnimplementedCriticServiceHandler) MarkConversationAs(context.Context, *connect.Request[api.MarkConversationAsRequest]) (*connect.Response[api.MarkConversationAsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.MarkConversationAs is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetDiffBases(context.Context, *connect.Request[api.GetDiffBasesRequest]) (*connect.Response[api.GetDiffBasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetDiffBases is not implemented"))
}

func (UnimplementedCriticServiceHandler) SetDiffBase(context.Context, *connect.Request[api.SetDiffBaseRequest]) (*connect.Response[api.SetDiffBaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.SetDiffBase is not implemented"))
}

func (UnimplementedCriticServiceHandler) WatchFile(context.Context, *connect.Request[api.WatchFileRequest]) (*connect.Response[api.WatchFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.WatchFile is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetConfig(context.Context, *connect.Request[api.GetConfigRequest]) (*connect.Response[api.GetConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetConfig is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetRootConversation(context.Context, *connect.Request[api.GetRootConversationRequest]) (*connect.Response[api.GetRootConversationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetRootConversation is not implemented"))
}

func (UnimplementedCriticServiceHandler) GetProjectConfig(context.Context, *connect.Request[api.GetProjectConfigRequest]) (*connect.Response[api.GetProjectConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.GetProjectConfig is not implemented"))
}

func (UnimplementedCriticServiceHandler) CreateExplanation(context.Context, *connect.Request[api.CreateExplanationRequest]) (*connect.Response[api.CreateExplanationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.CreateExplanation is not implemented"))
}

func (UnimplementedCriticServiceHandler) SetClaudeSession(context.Context, *connect.Request[api.SetClaudeSessionRequest]) (*connect.Response[api.SetClaudeSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.SetClaudeSession is not implemented"))
}

func (UnimplementedCriticServiceHandler) InjectPrompt(context.Context, *connect.Request[api.InjectPromptRequest]) (*connect.Response[api.InjectPromptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("critic.v1.CriticService.InjectPrompt is not implemented"))
}
