// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: critic.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetLastChangeRequest is an empty request for GetLastChange.
type GetLastChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastChangeRequest) Reset() {
	*x = GetLastChangeRequest{}
	mi := &file_critic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastChangeRequest) ProtoMessage() {}

func (x *GetLastChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastChangeRequest.ProtoReflect.Descriptor instead.
func (*GetLastChangeRequest) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{0}
}

// GetLastChangeResponse contains the timestamp of the last change.
type GetLastChangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mtime_msecs is the timestamp in milliseconds since Unix epoch.
	MtimeMsecs    uint64 `protobuf:"varint,1,opt,name=mtime_msecs,json=mtimeMsecs,proto3" json:"mtime_msecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastChangeResponse) Reset() {
	*x = GetLastChangeResponse{}
	mi := &file_critic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastChangeResponse) ProtoMessage() {}

func (x *GetLastChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastChangeResponse.ProtoReflect.Descriptor instead.
func (*GetLastChangeResponse) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastChangeResponse) GetMtimeMsecs() uint64 {
	if x != nil {
		return x.MtimeMsecs
	}
	return 0
}

var File_critic_proto protoreflect.FileDescriptor

const file_critic_proto_rawDesc = "" +
	"\n" +
	"\fcritic.proto\x12\tcritic.v1\"\x16\n" +
	"\x14GetLastChangeRequest\"8\n" +
	"\x15GetLastChangeResponse\x12\x1f\n" +
	"\vmtime_msecs\x18\x01 \x01(\x04R\n" +
	"mtimeMsecs2c\n" +
	"\rCriticService\x12R\n" +
	"\rGetLastChange\x12\x1f.critic.v1.GetLastChangeRequest\x1a .critic.v1.GetLastChangeResponseB#Z!git.15b.it/eno/critic/src/api;apib\x06proto3"

var (
	file_critic_proto_rawDescOnce sync.Once
	file_critic_proto_rawDescData []byte
)

func file_critic_proto_rawDescGZIP() []byte {
	file_critic_proto_rawDescOnce.Do(func() {
		file_critic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_critic_proto_rawDesc), len(file_critic_proto_rawDesc)))
	})
	return file_critic_proto_rawDescData
}

var file_critic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_critic_proto_goTypes = []any{
	(*GetLastChangeRequest)(nil),  // 0: critic.v1.GetLastChangeRequest
	(*GetLastChangeResponse)(nil), // 1: critic.v1.GetLastChangeResponse
}
var file_critic_proto_depIdxs = []int32{
	0, // 0: critic.v1.CriticService.GetLastChange:input_type -> critic.v1.GetLastChangeRequest
	1, // 1: critic.v1.CriticService.GetLastChange:output_type -> critic.v1.GetLastChangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_critic_proto_init() }
func file_critic_proto_init() {
	if File_critic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_critic_proto_rawDesc), len(file_critic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_critic_proto_goTypes,
		DependencyIndexes: file_critic_proto_depIdxs,
		MessageInfos:      file_critic_proto_msgTypes,
	}.Build()
	File_critic_proto = out.File
	file_critic_proto_goTypes = nil
	file_critic_proto_depIdxs = nil
}
