// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: critic.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FileStatus represents the status of a file in a diff.
type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_MODIFIED    FileStatus = 1
	FileStatus_FILE_STATUS_NEW         FileStatus = 2
	FileStatus_FILE_STATUS_DELETED     FileStatus = 3
	FileStatus_FILE_STATUS_RENAMED     FileStatus = 4
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_MODIFIED",
		2: "FILE_STATUS_NEW",
		3: "FILE_STATUS_DELETED",
		4: "FILE_STATUS_RENAMED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_MODIFIED":    1,
		"FILE_STATUS_NEW":         2,
		"FILE_STATUS_DELETED":     3,
		"FILE_STATUS_RENAMED":     4,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_critic_proto_enumTypes[0].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_critic_proto_enumTypes[0]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{0}
}

// LineType represents the type of a line in a diff.
type LineType int32

const (
	LineType_LINE_TYPE_UNSPECIFIED LineType = 0
	LineType_LINE_TYPE_CONTEXT     LineType = 1
	LineType_LINE_TYPE_ADDED       LineType = 2
	LineType_LINE_TYPE_DELETED     LineType = 3
)

// Enum value maps for LineType.
var (
	LineType_name = map[int32]string{
		0: "LINE_TYPE_UNSPECIFIED",
		1: "LINE_TYPE_CONTEXT",
		2: "LINE_TYPE_ADDED",
		3: "LINE_TYPE_DELETED",
	}
	LineType_value = map[string]int32{
		"LINE_TYPE_UNSPECIFIED": 0,
		"LINE_TYPE_CONTEXT":     1,
		"LINE_TYPE_ADDED":       2,
		"LINE_TYPE_DELETED":     3,
	}
)

func (x LineType) Enum() *LineType {
	p := new(LineType)
	*p = x
	return p
}

func (x LineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LineType) Descriptor() protoreflect.EnumDescriptor {
	return file_critic_proto_enumTypes[1].Descriptor()
}

func (LineType) Type() protoreflect.EnumType {
	return &file_critic_proto_enumTypes[1]
}

func (x LineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LineType.Descriptor instead.
func (LineType) EnumDescriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{1}
}

// GetLastChangeRequest is an empty request for GetLastChange.
type GetLastChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastChangeRequest) Reset() {
	*x = GetLastChangeRequest{}
	mi := &file_critic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastChangeRequest) ProtoMessage() {}

func (x *GetLastChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastChangeRequest.ProtoReflect.Descriptor instead.
func (*GetLastChangeRequest) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{0}
}

// GetLastChangeResponse contains the timestamp of the last change.
type GetLastChangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mtime_msecs is the timestamp in milliseconds since Unix epoch.
	MtimeMsecs    uint64 `protobuf:"varint,1,opt,name=mtime_msecs,json=mtimeMsecs,proto3" json:"mtime_msecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastChangeResponse) Reset() {
	*x = GetLastChangeResponse{}
	mi := &file_critic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastChangeResponse) ProtoMessage() {}

func (x *GetLastChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastChangeResponse.ProtoReflect.Descriptor instead.
func (*GetLastChangeResponse) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{1}
}

func (x *GetLastChangeResponse) GetMtimeMsecs() uint64 {
	if x != nil {
		return x.MtimeMsecs
	}
	return 0
}

// GetDiffsRequest is an empty request for GetDiffs.
type GetDiffsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffsRequest) Reset() {
	*x = GetDiffsRequest{}
	mi := &file_critic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffsRequest) ProtoMessage() {}

func (x *GetDiffsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffsRequest.ProtoReflect.Descriptor instead.
func (*GetDiffsRequest) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{2}
}

// GetDiffsResponse contains the current state and diffs from the session.
type GetDiffsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state is the current session state ("INITIALISING" or "READY").
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// diff contains the file diffs (may be null if state is INITIALISING).
	Diff          *Diff `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffsResponse) Reset() {
	*x = GetDiffsResponse{}
	mi := &file_critic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffsResponse) ProtoMessage() {}

func (x *GetDiffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffsResponse.ProtoReflect.Descriptor instead.
func (*GetDiffsResponse) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiffsResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetDiffsResponse) GetDiff() *Diff {
	if x != nil {
		return x.Diff
	}
	return nil
}

// Diff represents a git diff with multiple file changes.
type Diff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileDiff            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diff) Reset() {
	*x = Diff{}
	mi := &file_critic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diff) ProtoMessage() {}

func (x *Diff) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diff.ProtoReflect.Descriptor instead.
func (*Diff) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{4}
}

func (x *Diff) GetFiles() []*FileDiff {
	if x != nil {
		return x.Files
	}
	return nil
}

// FileDiff represents changes to a single file.
type FileDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	FileModeOld   string                 `protobuf:"bytes,3,opt,name=file_mode_old,json=fileModeOld,proto3" json:"file_mode_old,omitempty"`
	FileModeNew   string                 `protobuf:"bytes,4,opt,name=file_mode_new,json=fileModeNew,proto3" json:"file_mode_new,omitempty"`
	Status        FileStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=critic.v1.FileStatus" json:"status,omitempty"`
	IsBinary      bool                   `protobuf:"varint,6,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	Hunks         []*Hunk                `protobuf:"bytes,7,rep,name=hunks,proto3" json:"hunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDiff) Reset() {
	*x = FileDiff{}
	mi := &file_critic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDiff) ProtoMessage() {}

func (x *FileDiff) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDiff.ProtoReflect.Descriptor instead.
func (*FileDiff) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{5}
}

func (x *FileDiff) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileDiff) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *FileDiff) GetFileModeOld() string {
	if x != nil {
		return x.FileModeOld
	}
	return ""
}

func (x *FileDiff) GetFileModeNew() string {
	if x != nil {
		return x.FileModeNew
	}
	return ""
}

func (x *FileDiff) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileDiff) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *FileDiff) GetHunks() []*Hunk {
	if x != nil {
		return x.Hunks
	}
	return nil
}

// Hunk represents a chunk of changes within a file.
type Hunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldStart      int32                  `protobuf:"varint,1,opt,name=old_start,json=oldStart,proto3" json:"old_start,omitempty"`
	OldLines      int32                  `protobuf:"varint,2,opt,name=old_lines,json=oldLines,proto3" json:"old_lines,omitempty"`
	NewStart      int32                  `protobuf:"varint,3,opt,name=new_start,json=newStart,proto3" json:"new_start,omitempty"`
	NewLines      int32                  `protobuf:"varint,4,opt,name=new_lines,json=newLines,proto3" json:"new_lines,omitempty"`
	Header        string                 `protobuf:"bytes,5,opt,name=header,proto3" json:"header,omitempty"`
	Lines         []*Line                `protobuf:"bytes,6,rep,name=lines,proto3" json:"lines,omitempty"`
	Stats         *HunkStats             `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hunk) Reset() {
	*x = Hunk{}
	mi := &file_critic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunk) ProtoMessage() {}

func (x *Hunk) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunk.ProtoReflect.Descriptor instead.
func (*Hunk) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{6}
}

func (x *Hunk) GetOldStart() int32 {
	if x != nil {
		return x.OldStart
	}
	return 0
}

func (x *Hunk) GetOldLines() int32 {
	if x != nil {
		return x.OldLines
	}
	return 0
}

func (x *Hunk) GetNewStart() int32 {
	if x != nil {
		return x.NewStart
	}
	return 0
}

func (x *Hunk) GetNewLines() int32 {
	if x != nil {
		return x.NewLines
	}
	return 0
}

func (x *Hunk) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Hunk) GetLines() []*Line {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Hunk) GetStats() *HunkStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// HunkStats holds line statistics for a hunk.
type HunkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Deleted       int32                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HunkStats) Reset() {
	*x = HunkStats{}
	mi := &file_critic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HunkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HunkStats) ProtoMessage() {}

func (x *HunkStats) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HunkStats.ProtoReflect.Descriptor instead.
func (*HunkStats) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{7}
}

func (x *HunkStats) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *HunkStats) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

// Line represents a single line in a diff hunk.
type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          LineType               `protobuf:"varint,1,opt,name=type,proto3,enum=critic.v1.LineType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LineNoOld     int32                  `protobuf:"varint,3,opt,name=line_no_old,json=lineNoOld,proto3" json:"line_no_old,omitempty"`
	LineNoNew     int32                  `protobuf:"varint,4,opt,name=line_no_new,json=lineNoNew,proto3" json:"line_no_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_critic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_critic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_critic_proto_rawDescGZIP(), []int{8}
}

func (x *Line) GetType() LineType {
	if x != nil {
		return x.Type
	}
	return LineType_LINE_TYPE_UNSPECIFIED
}

func (x *Line) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Line) GetLineNoOld() int32 {
	if x != nil {
		return x.LineNoOld
	}
	return 0
}

func (x *Line) GetLineNoNew() int32 {
	if x != nil {
		return x.LineNoNew
	}
	return 0
}

var File_critic_proto protoreflect.FileDescriptor

const file_critic_proto_rawDesc = "" +
	"\n" +
	"\fcritic.proto\x12\tcritic.v1\"\x16\n" +
	"\x14GetLastChangeRequest\"8\n" +
	"\x15GetLastChangeResponse\x12\x1f\n" +
	"\vmtime_msecs\x18\x01 \x01(\x04R\n" +
	"mtimeMsecs\"\x11\n" +
	"\x0fGetDiffsRequest\"M\n" +
	"\x10GetDiffsResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12#\n" +
	"\x04diff\x18\x02 \x01(\v2\x0f.critic.v1.DiffR\x04diff\"1\n" +
	"\x04Diff\x12)\n" +
	"\x05files\x18\x01 \x03(\v2\x13.critic.v1.FileDiffR\x05files\"\xfb\x01\n" +
	"\bFileDiff\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\x12\"\n" +
	"\rfile_mode_old\x18\x03 \x01(\tR\vfileModeOld\x12\"\n" +
	"\rfile_mode_new\x18\x04 \x01(\tR\vfileModeNew\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.critic.v1.FileStatusR\x06status\x12\x1b\n" +
	"\tis_binary\x18\x06 \x01(\bR\bisBinary\x12%\n" +
	"\x05hunks\x18\a \x03(\v2\x0f.critic.v1.HunkR\x05hunks\"\xe5\x01\n" +
	"\x04Hunk\x12\x1b\n" +
	"\told_start\x18\x01 \x01(\x05R\boldStart\x12\x1b\n" +
	"\told_lines\x18\x02 \x01(\x05R\boldLines\x12\x1b\n" +
	"\tnew_start\x18\x03 \x01(\x05R\bnewStart\x12\x1b\n" +
	"\tnew_lines\x18\x04 \x01(\x05R\bnewLines\x12\x16\n" +
	"\x06header\x18\x05 \x01(\tR\x06header\x12%\n" +
	"\x05lines\x18\x06 \x03(\v2\x0f.critic.v1.LineR\x05lines\x12*\n" +
	"\x05stats\x18\a \x01(\v2\x14.critic.v1.HunkStatsR\x05stats\";\n" +
	"\tHunkStats\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x05R\adeleted\"\x89\x01\n" +
	"\x04Line\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.critic.v1.LineTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1e\n" +
	"\vline_no_old\x18\x03 \x01(\x05R\tlineNoOld\x12\x1e\n" +
	"\vline_no_new\x18\x04 \x01(\x05R\tlineNoNew*\x8a\x01\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FILE_STATUS_MODIFIED\x10\x01\x12\x13\n" +
	"\x0fFILE_STATUS_NEW\x10\x02\x12\x17\n" +
	"\x13FILE_STATUS_DELETED\x10\x03\x12\x17\n" +
	"\x13FILE_STATUS_RENAMED\x10\x04*h\n" +
	"\bLineType\x12\x19\n" +
	"\x15LINE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LINE_TYPE_CONTEXT\x10\x01\x12\x13\n" +
	"\x0fLINE_TYPE_ADDED\x10\x02\x12\x15\n" +
	"\x11LINE_TYPE_DELETED\x10\x032\xa8\x01\n" +
	"\rCriticService\x12R\n" +
	"\rGetLastChange\x12\x1f.critic.v1.GetLastChangeRequest\x1a .critic.v1.GetLastChangeResponse\x12C\n" +
	"\bGetDiffs\x12\x1a.critic.v1.GetDiffsRequest\x1a\x1b.critic.v1.GetDiffsResponseB*Z(github.com/radiospiel/critic/src/api;apib\x06proto3"

var (
	file_critic_proto_rawDescOnce sync.Once
	file_critic_proto_rawDescData []byte
)

func file_critic_proto_rawDescGZIP() []byte {
	file_critic_proto_rawDescOnce.Do(func() {
		file_critic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_critic_proto_rawDesc), len(file_critic_proto_rawDesc)))
	})
	return file_critic_proto_rawDescData
}

var file_critic_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_critic_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_critic_proto_goTypes = []any{
	(FileStatus)(0),               // 0: critic.v1.FileStatus
	(LineType)(0),                 // 1: critic.v1.LineType
	(*GetLastChangeRequest)(nil),  // 2: critic.v1.GetLastChangeRequest
	(*GetLastChangeResponse)(nil), // 3: critic.v1.GetLastChangeResponse
	(*GetDiffsRequest)(nil),       // 4: critic.v1.GetDiffsRequest
	(*GetDiffsResponse)(nil),      // 5: critic.v1.GetDiffsResponse
	(*Diff)(nil),                  // 6: critic.v1.Diff
	(*FileDiff)(nil),              // 7: critic.v1.FileDiff
	(*Hunk)(nil),                  // 8: critic.v1.Hunk
	(*HunkStats)(nil),             // 9: critic.v1.HunkStats
	(*Line)(nil),                  // 10: critic.v1.Line
}
var file_critic_proto_depIdxs = []int32{
	6,  // 0: critic.v1.GetDiffsResponse.diff:type_name -> critic.v1.Diff
	7,  // 1: critic.v1.Diff.files:type_name -> critic.v1.FileDiff
	0,  // 2: critic.v1.FileDiff.status:type_name -> critic.v1.FileStatus
	8,  // 3: critic.v1.FileDiff.hunks:type_name -> critic.v1.Hunk
	10, // 4: critic.v1.Hunk.lines:type_name -> critic.v1.Line
	9,  // 5: critic.v1.Hunk.stats:type_name -> critic.v1.HunkStats
	1,  // 6: critic.v1.Line.type:type_name -> critic.v1.LineType
	2,  // 7: critic.v1.CriticService.GetLastChange:input_type -> critic.v1.GetLastChangeRequest
	4,  // 8: critic.v1.CriticService.GetDiffs:input_type -> critic.v1.GetDiffsRequest
	3,  // 9: critic.v1.CriticService.GetLastChange:output_type -> critic.v1.GetLastChangeResponse
	5,  // 10: critic.v1.CriticService.GetDiffs:output_type -> critic.v1.GetDiffsResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_critic_proto_init() }
func file_critic_proto_init() {
	if File_critic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_critic_proto_rawDesc), len(file_critic_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_critic_proto_goTypes,
		DependencyIndexes: file_critic_proto_depIdxs,
		EnumInfos:         file_critic_proto_enumTypes,
		MessageInfos:      file_critic_proto_msgTypes,
	}.Build()
	File_critic_proto = out.File
	file_critic_proto_goTypes = nil
	file_critic_proto_depIdxs = nil
}
