package teapot

import (
	"reflect"
	"time"

	"git.15b.it/eno/critic/simple-go/logger"
	tea "github.com/charmbracelet/bubbletea"
)

// ComposerTickMsg is generated by the compositor to drive animations.
// This replaces all other tick messages in the codebase.
type ComposerTickMsg struct{}

// ComposerTickInterval is the tick rate for the compositor (40ms = 25fps).
const ComposerTickInterval = 40 * time.Millisecond

// GlobalTickCount is the global tick counter that animations use to compute their current frame.
// Each animation computes: frame = (GlobalTickCount / ticksPerFrame) % numFrames
// This is incremented by the compositor on each tick.
var GlobalTickCount int64

// globalTickSubscribers holds widgets that want to receive tick notifications
// when no Compositor is being used.
var globalTickSubscribers []TickHandler

// SubscribeToGlobalTicks registers a TickHandler to receive global tick notifications.
// Use this when not using a Compositor.
func SubscribeToGlobalTicks(handler TickHandler) {
	globalTickSubscribers = append(globalTickSubscribers, handler)
}

// UnsubscribeFromGlobalTicks removes a TickHandler from global tick notifications.
func UnsubscribeFromGlobalTicks(handler TickHandler) {
	for i, h := range globalTickSubscribers {
		if h == handler {
			globalTickSubscribers = append(globalTickSubscribers[:i], globalTickSubscribers[i+1:]...)
			return
		}
	}
}

// NotifyGlobalTickSubscribers notifies all global tick subscribers.
// Call this when handling ComposerTickMsg without a Compositor.
func NotifyGlobalTickSubscribers() {
	GlobalTickCount++
	// logger.Info("*** Notifying %d tick subscribers", len(globalTickSubscribers))
	for _, handler := range globalTickSubscribers {
		handler.HandleTick()
	}
}

// TickHandler is an interface for widgets that want to receive tick notifications.
// Widgets implementing this interface can subscribe to receive ticks via SubscribeToTicks.
type TickHandler interface {
	// HandleTick is called on each compositor tick.
	// The widget should update its state and call Repaint() if needed.
	HandleTick()
}

// Compositor manages the root widget tree and orchestrates rendering.
// It owns the screen buffer and handles the render loop.
type Compositor struct {
	root          Widget
	width, height int
	focusManager  *FocusManager
	dirty         bool // True if a re-render is needed

	// Layer management: top-level widgets sorted by z-order
	topLevelWidgets []Widget

	// Tick subscribers: widgets that want to receive tick notifications
	tickSubscribers []TickHandler

	// FPS measurement
	startTime  time.Time
	frameCount int64
}

// NewCompositor creates a new compositor with the given root widget.
func NewCompositor(root Widget) *Compositor {
	c := &Compositor{
		root:      root,
		dirty:     true,
		startTime: time.Now(),
	}
	if root != nil {
		c.focusManager = NewFocusManager(root)
		c.rebuildTopLevelWidgets()
	}
	return c
}

// SubscribeToTicks registers a TickHandler to receive tick notifications.
func (c *Compositor) SubscribeToTicks(handler TickHandler) {
	c.tickSubscribers = append(c.tickSubscribers, handler)
}

// UnsubscribeFromTicks removes a TickHandler from tick notifications.
func (c *Compositor) UnsubscribeFromTicks(handler TickHandler) {
	for i, h := range c.tickSubscribers {
		if h == handler {
			c.tickSubscribers = append(c.tickSubscribers[:i], c.tickSubscribers[i+1:]...)
			return
		}
	}
}

// HandleTick processes a compositor tick: checks for dirty widgets and continues ticking.
func (c *Compositor) HandleTick() tea.Cmd {
	// Advance the global tick counter
	GlobalTickCount++

	// Notify tick subscribers
	for _, handler := range c.tickSubscribers {
		handler.HandleTick()
	}

	// Check if any widget might be dirty
	logger.Info("*** checkDirtyWidgets")
	c.checkDirtyWidgets(c.root)

	// Continue ticking
	return tea.Tick(ComposerTickInterval, func(t time.Time) tea.Msg {
		return ComposerTickMsg{}
	})
}

// checkDirtyWidgets recursively checks widgets for MightBeDirty status.
func (c *Compositor) checkDirtyWidgets(w Widget) {
	if w == nil {
		return
	}
	if w.MightBeDirty() {
		c.dirty = true
	}
	for _, child := range w.Children() {
		c.checkDirtyWidgets(child)
	}
}

// RegisterTopLevelWidget adds a widget to the top-level widget list.
func (c *Compositor) RegisterTopLevelWidget(w Widget) {
	c.topLevelWidgets = append(c.topLevelWidgets, w)
}

// UnregisterTopLevelWidget removes a widget from the top-level widget list.
func (c *Compositor) UnregisterTopLevelWidget(w Widget) {
	for i := range c.topLevelWidgets {
		existing := c.topLevelWidgets[i]
		if existing == w {
			c.topLevelWidgets = append(c.topLevelWidgets[:i], c.topLevelWidgets[i+1:]...)
			return
		}
	}
}

// rebuildTopLevelWidgets rebuilds the list of top-level widgets from the root.
func (c *Compositor) rebuildTopLevelWidgets() {
	c.topLevelWidgets = nil
	if c.root != nil {
		c.topLevelWidgets = append(c.topLevelWidgets, c.root)
	}
}

// SetRoot sets the root widget.
func (c *Compositor) SetRoot(root Widget) {
	c.root = root
	if root != nil {
		root.SetBounds(Rect{X: 0, Y: 0, Width: c.width, Height: c.height})
		c.focusManager = NewFocusManager(root)
		c.rebuildTopLevelWidgets()
	} else {
		c.focusManager = nil
		c.topLevelWidgets = nil
	}
	c.dirty = true
}

// Root returns the root widget.
func (c *Compositor) Root() Widget {
	return c.root
}

// Resize handles terminal resize events.
func (c *Compositor) Resize(width, height int) {
	c.width = width
	c.height = height

	// Propagate size to root
	if c.root != nil {
		c.root.SetBounds(Rect{X: 0, Y: 0, Width: width, Height: height})
	}

	c.dirty = true
}

// Size returns the current screen size.
func (c *Compositor) Size() (width, height int) {
	return c.width, c.height
}

// MarkDirty marks the compositor as needing a re-render.
func (c *Compositor) MarkDirty() {
	c.dirty = true
}

// IsDirty returns true if the compositor needs a re-render.
func (c *Compositor) IsDirty() bool {
	return c.dirty
}

// Render renders the widget tree to the buffer and returns the string output.
// Widgets are rendered in z-order, and caching is used to avoid re-rendering
// widgets that haven't changed.
func (c *Compositor) Render() string {
	// FPS measurement
	c.frameCount++
	elapsed := time.Since(c.startTime).Seconds()
	if elapsed > 0 {
		fps := float64(c.frameCount) / elapsed
		logger.Info("FPS: %.1f (%d frames / %d sec)", fps, c.frameCount, int(elapsed))
	}

	if c.root == nil {
		logger.Info("%s %d ms", "compositor", int(0))
		return ""
	}

	// Reallocate buffers
	buffer := NewBuffer(c.width, c.height)

	// Iterate over top-level widgets by z-order (already sorted)
	for _, w := range c.topLevelWidgets {
		bounds := w.Bounds()

		widgetBuffer := renderWidgetIntoBuffer(w, bounds)
		buffer.Blit(widgetBuffer, bounds.X, bounds.Y)
	}

	// Save for next comparison
	c.dirty = false

	return buffer.RenderToString()
}

// CompositorDebug enables debug logging for the compositor
var CompositorDebug = false

func compositorLog(format string, args ...interface{}) {
	if CompositorDebug {
		logger.Info("[compositor] "+format, args...)
	}
}

// widgetTypeName returns the type name of a widget using reflection.
// If the widget has a non-empty Name(), that is returned instead.
func widgetTypeName(w Widget) string {
	if name := w.Name(); name != "" {
		return name
	}
	t := reflect.TypeOf(w)
	if t.Kind() == reflect.Ptr {
		return t.Elem().Name()
	}
	return t.Name()
}

// RenderWidget renders a widget with its border (if any) to the given buffer.
// This is the main rendering function that should be used to render widgets.
// It handles:
// 1. Rendering the widget's border (if configured)
// 2. Rendering the border title and footer
// 3. Calling the widget's Render method for the content area
func renderWidgetIntoBuffer(w Widget, bounds Rect) *Buffer {
	wb := NewBuffer(bounds.Width, bounds.Height)
	// TODO: do we really need a Sub here?
	RenderWidget(w, wb.Sub(bounds))
	return wb
}

func RenderWidget(w Widget, buf *SubBuffer) {
	// TODO: this method should probably be refactored into an instance
	// method, but various implementations are using it.
	logger.Runtime("RenderWidget "+widgetTypeName(w), func() bool {
		renderWidgetWoLogging(w, buf)
		return true
	})
}

func renderWidgetWoLogging(w Widget, buf *SubBuffer) {
	border := w.Border()

	// Render border if configured
	if border.HasBorder() {
		RenderBorder(buf, border)

		// Render title and footer
		if title := w.BorderTitle(); title != "" {
			RenderBorderTitle(buf, title, border.Style)
		}
		if footer := w.BorderFooter(); footer != "" {
			RenderBorderFooter(buf, footer, border.Style)
		}

		// Get content bounds for the widget's render
		contentBounds := Rect{
			X:      border.LeftWidth(),
			Y:      border.TopWidth(),
			Width:  buf.Width() - border.LeftWidth() - border.RightWidth(),
			Height: buf.Height() - border.TopWidth() - border.BottomWidth(),
		}

		if contentBounds.Width > 0 && contentBounds.Height > 0 {
			contentSub := buf.parent.Sub(Rect{
				X:      buf.offset.X + contentBounds.X,
				Y:      buf.offset.Y + contentBounds.Y,
				Width:  contentBounds.Width,
				Height: contentBounds.Height,
			})
			w.Render(contentSub)
		}
	} else {
		// No border, render directly
		w.Render(buf)
	}
}

// View returns the rendered output (for BubbleTea compatibility).
func (c *Compositor) View() string {
	return c.Render()
}

// HandleKey routes key events through the focus manager.
func (c *Compositor) HandleKey(msg tea.KeyMsg) (bool, tea.Cmd) {
	if c.focusManager != nil {
		return c.focusManager.HandleKey(msg)
	}
	return false, nil
}

// HandleMouse routes mouse events to the widget under the cursor.
func (c *Compositor) HandleMouse(msg tea.MouseMsg) (bool, tea.Cmd) {
	if c.root == nil {
		return false, nil
	}
	return c.routeMouseEvent(c.root, msg)
}

func (c *Compositor) routeMouseEvent(w Widget, msg tea.MouseMsg) (bool, tea.Cmd) {
	bounds := w.Bounds()
	if !bounds.Contains(msg.X, msg.Y) {
		return false, nil
	}

	// Check children first (reverse order for proper z-ordering)
	children := w.Children()
	for i := len(children) - 1; i >= 0; i-- {
		if handled, cmd := c.routeMouseEvent(children[i], msg); handled {
			return handled, cmd
		}
	}

	// Then the widget itself
	return w.HandleMouse(msg)
}

// FocusManager returns the focus manager.
func (c *Compositor) FocusManager() *FocusManager {
	return c.focusManager
}

// SetFocused sets focus to a specific widget.
func (c *Compositor) SetFocused(w Widget) {
	if c.focusManager != nil {
		c.focusManager.SetFocused(w)
	}
}

// Focused returns the currently focused widget.
func (c *Compositor) Focused() Widget {
	if c.focusManager != nil {
		return c.focusManager.Focused()
	}
	return nil
}

// RebuildFocusChain rebuilds the focus chain after widget tree changes.
func (c *Compositor) RebuildFocusChain() {
	if c.focusManager != nil {
		c.focusManager.RebuildFocusChain()
	}
}

// Update handles BubbleTea messages and returns commands.
// This is the main integration point with BubbleTea.
func (c *Compositor) Update(msg tea.Msg) tea.Cmd {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		c.Resize(msg.Width, msg.Height)
		return nil

	case tea.KeyMsg:
		_, cmd := c.HandleKey(msg)
		c.dirty = true
		return cmd

	case tea.MouseMsg:
		_, cmd := c.HandleMouse(msg)
		c.dirty = true
		return cmd

	case ComposerTickMsg:
		return c.HandleTick()
	}

	return nil
}

// CompositorModel wraps a Compositor as a full BubbleTea Model.
// Use this when you want the compositor to be the entire application.
type CompositorModel struct {
	compositor *Compositor
}

// NewCompositorModel creates a new BubbleTea model wrapping a compositor.
func NewCompositorModel(root Widget) CompositorModel {
	return CompositorModel{
		compositor: NewCompositor(root),
	}
}

// Compositor returns the underlying compositor.
func (m CompositorModel) Compositor() *Compositor {
	return m.compositor
}

// Init implements tea.Model.
func (m CompositorModel) Init() tea.Cmd {
	return tea.Tick(ComposerTickInterval, func(t time.Time) tea.Msg {
		return ComposerTickMsg{}
	})
}

// Update implements tea.Model.
func (m CompositorModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c":
			return m, tea.Quit
		}
	}

	cmd := m.compositor.Update(msg)
	return m, cmd
}

// View implements tea.Model.
func (m CompositorModel) View() string {
	return m.compositor.View()
}
