package teapot

import (
	"sort"
	"time"

	tea "github.com/charmbracelet/bubbletea"
)

// ComposerTickMsg is generated by the compositor to drive animations.
// This replaces all other tick messages in the codebase.
type ComposerTickMsg struct{}

// ComposerTickInterval is the tick rate for the compositor (40ms = 25fps).
const ComposerTickInterval = 40 * time.Millisecond

// GlobalTickCount is the global tick counter that animations use to compute their current frame.
// Each animation computes: frame = (GlobalTickCount / ticksPerFrame) % numFrames
// This is incremented by the compositor on each tick.
var GlobalTickCount int64

// Compositor manages the root widget tree and orchestrates rendering.
// It owns the screen buffer and handles the render loop.
type Compositor struct {
	root          Widget
	width, height int
	buffer        *Buffer
	prevBuffer    *Buffer
	focusManager  *FocusManager
	dirty         bool // True if a re-render is needed

	// Layer management: top-level widgets sorted by z-order
	topLevelWidgets []Widget
}

// NewCompositor creates a new compositor with the given root widget.
func NewCompositor(root Widget) *Compositor {
	c := &Compositor{
		root:  root,
		dirty: true,
	}
	if root != nil {
		c.focusManager = NewFocusManager(root)
		c.rebuildTopLevelWidgets()
	}
	return c
}

// HandleTick processes a compositor tick: checks for dirty widgets and continues ticking.
func (c *Compositor) HandleTick() tea.Cmd {
	// Advance the global tick counter
	GlobalTickCount++

	// Check if any widget might be dirty
	c.checkDirtyWidgets(c.root)

	// Continue ticking
	return tea.Tick(ComposerTickInterval, func(t time.Time) tea.Msg {
		return ComposerTickMsg{}
	})
}

// checkDirtyWidgets recursively checks widgets for MightBeDirty status.
func (c *Compositor) checkDirtyWidgets(w Widget) {
	if w == nil {
		return
	}
	if w.MightBeDirty() {
		c.dirty = true
	}
	for _, child := range w.Children() {
		c.checkDirtyWidgets(child)
	}
}

// RegisterTopLevelWidget adds a widget to the top-level widget list.
func (c *Compositor) RegisterTopLevelWidget(w Widget) {
	c.topLevelWidgets = append(c.topLevelWidgets, w)
	c.sortTopLevelWidgets()
}

// UnregisterTopLevelWidget removes a widget from the top-level widget list.
func (c *Compositor) UnregisterTopLevelWidget(w Widget) {
	for i, existing := range c.topLevelWidgets {
		if existing == w {
			c.topLevelWidgets = append(c.topLevelWidgets[:i], c.topLevelWidgets[i+1:]...)
			if cw, ok := w.(cacheableWidget); ok {
				cw.SetCachedView(nil) // Clear the widget's cache
			}
			return
		}
	}
}

// rebuildTopLevelWidgets rebuilds the list of top-level widgets from the root.
func (c *Compositor) rebuildTopLevelWidgets() {
	c.topLevelWidgets = nil
	if c.root != nil {
		c.topLevelWidgets = append(c.topLevelWidgets, c.root)
	}
	c.sortTopLevelWidgets()
}

// sortTopLevelWidgets sorts top-level widgets by z-order.
func (c *Compositor) sortTopLevelWidgets() {
	sort.Slice(c.topLevelWidgets, func(i, j int) bool {
		return c.topLevelWidgets[i].ZOrder() < c.topLevelWidgets[j].ZOrder()
	})
}

// SetRoot sets the root widget.
func (c *Compositor) SetRoot(root Widget) {
	// Clear cache on old widgets
	c.clearWidgetCaches(c.root)
	c.root = root
	if root != nil {
		root.SetBounds(Rect{X: 0, Y: 0, Width: c.width, Height: c.height})
		c.focusManager = NewFocusManager(root)
		c.rebuildTopLevelWidgets()
	} else {
		c.focusManager = nil
		c.topLevelWidgets = nil
	}
	c.dirty = true
}

// clearWidgetCaches clears cached views on a widget and its children.
func (c *Compositor) clearWidgetCaches(w Widget) {
	if w == nil {
		return
	}
	if cw, ok := w.(cacheableWidget); ok {
		cw.SetCachedView(nil)
	}
	for _, child := range w.Children() {
		c.clearWidgetCaches(child)
	}
}

// Root returns the root widget.
func (c *Compositor) Root() Widget {
	return c.root
}

// Resize handles terminal resize events.
func (c *Compositor) Resize(width, height int) {
	c.width = width
	c.height = height

	// Reallocate buffers
	c.buffer = NewBuffer(width, height)
	c.prevBuffer = nil // Force full redraw

	// Clear widget caches as sizes have changed
	c.clearWidgetCaches(c.root)

	// Propagate size to root
	if c.root != nil {
		c.root.SetBounds(Rect{X: 0, Y: 0, Width: width, Height: height})
	}

	c.dirty = true
}

// Size returns the current screen size.
func (c *Compositor) Size() (width, height int) {
	return c.width, c.height
}

// MarkDirty marks the compositor as needing a re-render.
func (c *Compositor) MarkDirty() {
	c.dirty = true
}

// IsDirty returns true if the compositor needs a re-render.
func (c *Compositor) IsDirty() bool {
	return c.dirty
}

// Render renders the widget tree to the buffer and returns the string output.
// Widgets are rendered in z-order, and caching is used to avoid re-rendering
// widgets that haven't changed.
func (c *Compositor) Render() string {
	if c.buffer == nil || c.root == nil {
		return ""
	}

	// Clear the output buffer
	c.buffer.Clear()

	// Iterate over top-level widgets by z-order (already sorted)
	for _, w := range c.topLevelWidgets {
		c.renderWidgetWithCache(w)
	}

	// Save for next comparison
	c.prevBuffer = c.buffer.Clone()
	c.dirty = false

	return c.buffer.String()
}

// renderWidgetWithCache renders a widget, using its cache if available.
// The cache is accessed via the internal cacheableWidget interface.
// Widgets that embed BaseWidget automatically support caching.
func (c *Compositor) renderWidgetWithCache(w Widget) {
	bounds := w.Bounds()
	needsRender := w.MightBeDirty() // MightBeDirty() returns true if dirty or animated

	// Try to use caching if the widget supports it
	cw, canCache := w.(cacheableWidget)
	if !canCache {
		// Widget doesn't support caching, render directly
		buf := NewBuffer(bounds.Width, bounds.Height)
		buf.Clear()
		sub := buf.Sub(buf.Bounds())
		RenderWidget(w, sub)
		c.buffer.Blit(buf, bounds.X, bounds.Y)
		return
	}

	// Check if we have a cached buffer in the widget
	cached := cw.CachedView()
	if cached == nil || needsRender {
		// Create or resize the cache buffer
		if cached == nil || cached.Width() != bounds.Width || cached.Height() != bounds.Height {
			cached = NewBuffer(bounds.Width, bounds.Height)
		}

		// Clear and render to cache
		cached.Clear()
		sub := cached.Sub(cached.Bounds())
		RenderWidget(w, sub)

		// SetCachedView clears the dirty flag automatically
		cw.SetCachedView(cached)
	}

	// Blit the cached buffer to the output
	c.buffer.Blit(cached, bounds.X, bounds.Y)
}

// RenderWidget renders a widget with its border (if any) to the given buffer.
// This is the main rendering function that should be used to render widgets.
// It handles:
// 1. Rendering the widget's border (if configured)
// 2. Rendering the border title and footer
// 3. Calling the widget's Render method for the content area
func RenderWidget(w Widget, buf *SubBuffer) {
	border := w.Border()

	// Render border if configured
	if border.HasBorder() {
		RenderBorder(buf, border)

		// Render title and footer
		if title := w.BorderTitle(); title != "" {
			RenderBorderTitle(buf, title, border.Style)
		}
		if footer := w.BorderFooter(); footer != "" {
			RenderBorderFooter(buf, footer, border.Style)
		}

		// Get content bounds for the widget's render
		contentBounds := Rect{
			X:      border.LeftWidth(),
			Y:      border.TopWidth(),
			Width:  buf.Width() - border.LeftWidth() - border.RightWidth(),
			Height: buf.Height() - border.TopWidth() - border.BottomWidth(),
		}

		if contentBounds.Width > 0 && contentBounds.Height > 0 {
			contentSub := buf.parent.Sub(Rect{
				X:      buf.offset.X + contentBounds.X,
				Y:      buf.offset.Y + contentBounds.Y,
				Width:  contentBounds.Width,
				Height: contentBounds.Height,
			})
			w.Render(contentSub)
		}
	} else {
		// No border, render directly
		w.Render(buf)
	}
}

// View returns the rendered output (for BubbleTea compatibility).
func (c *Compositor) View() string {
	return c.Render()
}

// HandleKey routes key events through the focus manager.
func (c *Compositor) HandleKey(msg tea.KeyMsg) (bool, tea.Cmd) {
	if c.focusManager != nil {
		return c.focusManager.HandleKey(msg)
	}
	return false, nil
}

// HandleMouse routes mouse events to the widget under the cursor.
func (c *Compositor) HandleMouse(msg tea.MouseMsg) (bool, tea.Cmd) {
	if c.root == nil {
		return false, nil
	}
	return c.routeMouseEvent(c.root, msg)
}

func (c *Compositor) routeMouseEvent(w Widget, msg tea.MouseMsg) (bool, tea.Cmd) {
	bounds := w.Bounds()
	if !bounds.Contains(msg.X, msg.Y) {
		return false, nil
	}

	// Check children first (reverse order for proper z-ordering)
	children := w.Children()
	for i := len(children) - 1; i >= 0; i-- {
		if handled, cmd := c.routeMouseEvent(children[i], msg); handled {
			return handled, cmd
		}
	}

	// Then the widget itself
	return w.HandleMouse(msg)
}

// FocusManager returns the focus manager.
func (c *Compositor) FocusManager() *FocusManager {
	return c.focusManager
}

// SetFocused sets focus to a specific widget.
func (c *Compositor) SetFocused(w Widget) {
	if c.focusManager != nil {
		c.focusManager.SetFocused(w)
	}
}

// Focused returns the currently focused widget.
func (c *Compositor) Focused() Widget {
	if c.focusManager != nil {
		return c.focusManager.Focused()
	}
	return nil
}

// RebuildFocusChain rebuilds the focus chain after widget tree changes.
func (c *Compositor) RebuildFocusChain() {
	if c.focusManager != nil {
		c.focusManager.RebuildFocusChain()
	}
}

// Update handles BubbleTea messages and returns commands.
// This is the main integration point with BubbleTea.
func (c *Compositor) Update(msg tea.Msg) tea.Cmd {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		c.Resize(msg.Width, msg.Height)
		return nil

	case tea.KeyMsg:
		_, cmd := c.HandleKey(msg)
		c.dirty = true
		return cmd

	case tea.MouseMsg:
		_, cmd := c.HandleMouse(msg)
		c.dirty = true
		return cmd

	case ComposerTickMsg:
		return c.HandleTick()
	}

	return nil
}

// CompositorModel wraps a Compositor as a full BubbleTea Model.
// Use this when you want the compositor to be the entire application.
type CompositorModel struct {
	compositor *Compositor
}

// NewCompositorModel creates a new BubbleTea model wrapping a compositor.
func NewCompositorModel(root Widget) CompositorModel {
	return CompositorModel{
		compositor: NewCompositor(root),
	}
}

// Compositor returns the underlying compositor.
func (m CompositorModel) Compositor() *Compositor {
	return m.compositor
}

// Init implements tea.Model.
func (m CompositorModel) Init() tea.Cmd {
	return tea.Tick(ComposerTickInterval, func(t time.Time) tea.Msg {
		return ComposerTickMsg{}
	})
}

// Update implements tea.Model.
func (m CompositorModel) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c":
			return m, tea.Quit
		}
	}

	cmd := m.compositor.Update(msg)
	return m, cmd
}

// View implements tea.Model.
func (m CompositorModel) View() string {
	return m.compositor.View()
}
